version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a day
    schedule:
      interval: "daily"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "npm"
      - "security"
    # Group all updates together
    groups:
      dependencies:
        patterns:
          - "*"
    # Set the version update strategy
    versioning-strategy: auto
    # Allow up to 10 open pull requests for dependencies
    open-pull-requests-limit: 10
    # Specify the target branch for pull requests
    target-branch: "main"
    # Automatically merge minor and patch updates
    commit-message:
      prefix: "npm"
      include: "scope"
    # More intelligent ignore rules
    ignore:
      # Ignore major version updates for specific packages that might break things
      - dependency-name: "astro"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@astrojs/*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tailwindcss"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@tailwindcss/*"
        update-types: ["version-update:semver-major"]
      # Allow major updates for security-focused packages
      - dependency-name: "marked"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
      - dependency-name: "shiki"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    open-pull-requests-limit: 5
    target-branch: "main"
    commit-message:
      prefix: "ci"
      include: "scope"
