version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    # Check for updates once a day
    schedule:
      interval: "daily"
    # Specify labels for pull requests
    labels:
      - "dependencies"
      - "npm"
      - "security"
    # Group all updates together
    groups:
      dependencies:
        patterns:
          - "*"
    # Set the version update strategy
    versioning-strategy: auto
    # Allow up to 10 open pull requests for dependencies
    open-pull-requests-limit: 10
    # Specify the target branch for pull requests
    target-branch: "main"
    # Set reviewers for the pull requests
    reviewers:
      - "Bearloggs"
    # Automatically merge minor and patch updates
    commit-message:
      prefix: "npm"
      include: "scope"
    ignore:
      # Ignore major version updates for specific packages
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
