name: Test and Security

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run check

      - name: Format check
        run: npx prettier --check .

      - name: Build
        run: npm run build

      - name: Test
        run: npm test

      # Security checks - only run on PRs with security label
      - name: Run security audit
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'security')
        run: npm audit --audit-level=moderate

      - name: Check for known vulnerabilities
        if: github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'security')
        run: npx audit-ci --moderate
